# Generated by Django 5.0.6 on 2024-07-14 14:53

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='unknown', max_length=100, unique=True, verbose_name='Nombre de usuario')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('password', models.CharField(max_length=100, verbose_name='Contraseña')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('activo', models.BooleanField(default=True, null=True, verbose_name='Activo')),
                ('usuario_administrador', models.BooleanField(default=False)),
                ('connection_count', models.IntegerField(default=0)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_ping', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SessionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaContrato', models.DateField()),
                ('fechaVencimientoActual', models.DateField(default=datetime.date.today)),
                ('debe', models.BooleanField(default=True, null=True)),
                ('cuota', models.PositiveIntegerField()),
                ('dispositivos', models.PositiveSmallIntegerField(default=3)),
                ('nombre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'db_table': 'contrato',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaPago', models.DateField()),
                ('fechaVencimiento', models.DateField()),
                ('saldo', models.PositiveIntegerField()),
                ('pago', models.PositiveIntegerField()),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pagos',
                'ordering': ['id'],
            },
        ),
    ]
