# Generated by Django 4.2.14 on 2024-07-27 22:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publiApp', '0002_alter_cliente_username_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
