# Generated by Django 4.2.14 on 2024-09-01 21:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publiApp', '0004_customsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsession',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
