# Generated by Django 4.2.14 on 2024-09-02 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publiApp', '0006_alter_customsession_session_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SessionInfo',
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
